// backend/supabase/functions/narrate-domains-pattern/index.ts
// MBI Phase 1.5 — Domain Pattern Narrative Edge Function
// Sprint 3B · Domains Tab
// Receives structured pattern detection output → returns pattern title, body, synthesis line.
// Claude generates copy only. All pattern detection and role assignment happens before this call.
// Prompt Version: 1.1  ← Audit: response tone scaffold

import { serve } from "https://deno.land/std@0.177.0/http/server.ts";
import { verifyCallerOwnsUser } from "../../functions/_shared/auth.ts";

const ANTHROPIC_API_KEY = Deno.env.get("ANTHROPIC_API_KEY")!;

const MODEL = "claude-sonnet-4-6";
const PROMPT_VERSION = "1.3";

// ─────────────────────────────────────────
// TYPES
// ─────────────────────────────────────────

type PatternType =
  | "load_outpacing_recovery"
  | "hidden_stress_signal"
  | "sleep_protecting_recovery"
  | "systems_in_alignment"
  | "recovery_under_pressure"
  | "default";

interface DomainPatternInput {
  userId: string;               // required for auth verification
  pattern_type: PatternType;
  driver_domain: string;        // e.g. "D1"
  buffer_domain: string | null;
  watch_domain: string | null;
  domain_scores: {
    d1?: number | null;
    d2?: number | null;
    d3?: number | null;
    d4?: number | null;
    d5?: number | null;
  };
  days_of_history: number;
}

// ─────────────────────────────────────────
// DOMAIN LABELS
// ─────────────────────────────────────────

const DOMAIN_LABELS: Record<string, string> = {
  D1: "autonomic recovery",
  D2: "sleep recovery",
  D3: "activity load",
  D4: "inferred stress",
  D5: "allostatic trend",
};

// ─────────────────────────────────────────
// PATTERN CONTEXT
// Plain-language descriptions of what each pattern means physiologically.
// Passed to Claude as structured context — not generated by Claude.
// ─────────────────────────────────────────

const PATTERN_CONTEXT: Record<PatternType, string> = {
  load_outpacing_recovery:
    "Physical activity is high relative to the user's baseline, but the autonomic nervous system has not recovered to match it. The body is absorbing load faster than it is recovering. Sleep may be compensating but has not closed the gap.",
  hidden_stress_signal:
    "A stress pattern is accumulating in the 7-day window despite sleep holding steady. The autonomic system is slightly suppressed. The composite score may look moderate but underlying stress is building.",
  sleep_protecting_recovery:
    "Sleep quality and duration are above the user's baseline. The autonomic system is below baseline, but sleep is providing the primary recovery buffer. The body is in a compensation state — sleep is doing the heavy lifting.",
  systems_in_alignment:
    "All active domains are performing near or above the user's personal baseline, and they are within a close range of each other. The body is in a balanced, coherent state today.",
  recovery_under_pressure:
    "Both the autonomic system and the stress pattern domain are below baseline simultaneously. The body is managing a recovery deficit while stress load is elevated. This is a compound pressure state.",
  default:
    "One domain is leading today's pattern as the primary driver of the composite score. The other domains are in a supporting or stable state.",
};

// ─────────────────────────────────────────
// RESPONSE TONE SCAFFOLD (Audit §4.2)
// Hardcoded 'balanced' for Phase 1. Phase 2 reads from users table preference.
// ─────────────────────────────────────────

const TONE_INSTRUCTIONS: Record<string, string> = {
  balanced:     "Calm, direct, observational framing. The user should feel legible to themselves, not analysed. This is the default register.",
  clinical:     "Metric-forward, no metaphor. Pattern type and mechanism named directly.",
  motivational: "Frame the observation as momentum or load context. No instructions — observe only.",
};

// ─────────────────────────────────────────
// PROMPT BUILDER
// ─────────────────────────────────────────

function buildPrompt(input: DomainPatternInput): string {
  const driverLabel    = DOMAIN_LABELS[input.driver_domain] ?? input.driver_domain;
  const bufferLabel    = input.buffer_domain ? DOMAIN_LABELS[input.buffer_domain] : null;
  const watchLabel     = input.watch_domain  ? DOMAIN_LABELS[input.watch_domain]  : null;
  const patternContext = PATTERN_CONTEXT[input.pattern_type];
  const toneInstruction = TONE_INSTRUCTIONS["balanced"];  // ← Audit §4.2: Phase 2 reads from users table

  const scoreLines = Object.entries(input.domain_scores)
    .filter(([, v]) => v != null)
    .map(([k, v]) => `  ${DOMAIN_LABELS[k.toUpperCase()] ?? k}: ${Math.round(v as number)}`)
    .join("\n");

  const roleLines = [
    `Largest deviation (drag on score): ${driverLabel}`,
    bufferLabel ? `Strongest positive (above baseline): ${bufferLabel}` : null,
    watchLabel  ? `In watch state: ${watchLabel}` : null,
  ].filter(Boolean).join("\n");

  return `You are the voice of Mynd & Bodi Institute, a prevention-first health intelligence platform.

Your role is to name what the body is doing today across five biological systems. You observe. You do not advise.

ABSOLUTE RULES — NEVER VIOLATE:
- Never use clinical language or diagnostic framing
- Never say "autonomic dysfunction", "systemic inflammation", "pathological", "risk factor", or any medical diagnostic term
- Never say "consult a physician" or suggest medical evaluation
- Never tell the user what to do — this tab observes only, it does not give behavioral nudges
- Always use wellness framing: recovery, resilience, load, patterns, balance
- Within-user context only — never reference population averages or norms
- Tone: calm, direct, informative. The user should feel legible to themselves, not alarmed.

TODAY'S SYSTEM PATTERN:
Pattern type: ${input.pattern_type}
${patternContext}

Domain roles today:
${roleLines}

Domain scores (user's own baseline scale, 0–100):
${scoreLines}

Days of history: ${input.days_of_history}

Generate exactly three outputs:

PATTERN_TITLE: Maximum 6 words. No punctuation. Names the dominant pattern today. Plain language. Example: "Load outpacing recovery" or "Systems in alignment". Do not use the words DRIVER, ELEVATED, or PRIMARY DRIVER.

PATTERN_BODY: Maximum 3 sentences. Observational only — names the pattern, identifies which systems are involved, explains what that means in plain wellness language. No advice. No instructions. Do not use the words DRIVER, ELEVATED, or PRIMARY DRIVER.

SYNTHESIS_LINE: Exactly 1 sentence. 40 tokens maximum. The one thing the user carries out of this tab. Summarises what all five systems are collectively saying today. Written as a direct observation — no advice. No em dashes. The synthesis line must be a different formulation from the pattern_body. Do not repeat any sentence from pattern_body. Offer a different angle on the same data — a complementary observation, not a restatement.

RESPONSE TONE (balanced): ${toneInstruction}

Respond in this exact JSON format:
{
  "pattern_title": "...",
  "pattern_body": "...",
  "synthesis_line": "..."
}`;
}

// ─────────────────────────────────────────
// HANDLER
// ─────────────────────────────────────────

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders() });
  }

  try {
    const body = await req.json() as DomainPatternInput;

    const { userId, pattern_type, driver_domain, domain_scores } = body;

    if (!userId) {
      return new Response(
        JSON.stringify({ error: "userId required" }),
        { status: 400, headers: { "Content-Type": "application/json", ...corsHeaders() } }
      );
    }

    const authErr = await verifyCallerOwnsUser(req, userId);
    if (authErr !== null) return authErr;

    if (!pattern_type || !driver_domain || !domain_scores) {
      return new Response(
        JSON.stringify({ error: "Missing required fields: pattern_type, driver_domain, domain_scores" }),
        { status: 400, headers: { "Content-Type": "application/json", ...corsHeaders() } }
      );
    }

    const prompt = buildPrompt(body);

    // ── Call Claude API ───────────────────────────────────────────────
    const claudeResponse = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 300,
        system: "You are the Mynd & Bodi Institute wellness voice. Observe only — never advise. Never use clinical language. Respond only with the JSON object requested. No preamble. No markdown.",
        messages: [{ role: "user", content: prompt }],
      }),
    });

    if (!claudeResponse.ok) {
      const err = await claudeResponse.text();
      throw new Error(`Claude API error: ${err}`);
    }

    const claudeData = await claudeResponse.json();
    const rawText = (claudeData.content?.[0]?.text ?? "").trim();

    let parsed: { pattern_title: string; pattern_body: string; synthesis_line: string };
    try {
      const jsonMatch = rawText.match(/\{[\s\S]*\}/);
      parsed = JSON.parse(jsonMatch?.[0] ?? rawText);
    } catch {
      // Fallback — should not occur in practice
      parsed = {
        pattern_title: "System read",
        pattern_body: "Your systems are active today. One domain is leading the pattern.",
        synthesis_line: "Your body is working through its current state.",
      };
    }

    return new Response(
      JSON.stringify({
        success: true,
        pattern_title: parsed.pattern_title,
        pattern_body: parsed.pattern_body,
        synthesis_line: parsed.synthesis_line,
        prompt_version: PROMPT_VERSION,
        model_version: MODEL,
      }),
      { headers: { "Content-Type": "application/json", ...corsHeaders() } }
    );

  } catch (err) {
    console.error("[narrate-domains-pattern]", err);
    return new Response(
      JSON.stringify({ error: String(err) }),
      { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders() } }
    );
  }
});

function corsHeaders() {
  return {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "authorization, content-type",
  };
}