-- Migration: 20260520000003_explanations_detail_fields
-- Step 9a: Add detail narrative columns to explanations table.
-- Supports narrate-detail Edge Function (Step 9b). Purely additive — no existing columns modified.

ALTER TABLE public.explanations
  ADD COLUMN IF NOT EXISTS detail_explanation_text text NULL,
  ADD COLUMN IF NOT EXISTS detail_generated_at timestamptz NULL;

COMMENT ON COLUMN public.explanations.detail_explanation_text IS
  'Full 7-day system narrative generated by narrate-detail function.
   Null until narrate-detail has run for this date.';

COMMENT ON COLUMN public.explanations.detail_generated_at IS
  'Timestamp when narrate-detail last wrote to this row.
   Used to detect stale detail narratives.';
